[package]
name = "pyrite-protocol"
description = "Clean-room Minecraft-compatible network protocol codecs for Pyrite."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "pyrite_protocol"

[dependencies]
bytes.workspace = true
flate2.workspace = true
tokio-util.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
pyrite-nbt.workspace = true

[lints]
workspace = true
